/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package minigames;

import java.util.LinkedList;
import java.util.Random;
import java.util.Vector;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.AbstractDocument;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;

/**
 *
 * @author IT
 */
public class Turnament extends javax.swing.JFrame {

    /**
     * Creates new form Aritmatika
     */
    public Turnament() {
        initComponents();
        // set only number can fill ans
        ((AbstractDocument)ans.getDocument()).setDocumentFilter(new NumericDocumentFilter());
        qtySkip.setText("Kesempatan skip : "+Integer.toString(this.skip));
        run();
    }
    
    int qtySoal = 0;
    
    public Turnament(int qtySoal) {
        
        this.qtySoal = qtySoal;
        
        initComponents();
        // set only number can fill ans
        ((AbstractDocument)ans.getDocument()).setDocumentFilter(new NumericDocumentFilter());
        qtySkip.setText("Kesempatan skip : "+Integer.toString(this.skip));
        run();
    }
    
    String qst = "";
    int result = 0;
    boolean tf = true;
    LinkedList<HasilTest> hasilTestList = new LinkedList<>();
    int skip = 2;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        qstText = new javax.swing.JLabel();
        ans = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        qtySkip = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        freeTest = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        turnament = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        qstText.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        qstText.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        qstText.setText("question");

        ans.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        ans.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        ans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ansActionPerformed(evt);
            }
        });
        ans.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ansKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("=");

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Check");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Skip");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        qtySkip.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        qtySkip.setText("Kesempatan skip :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(qstText)
                .addGap(44, 44, 44)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(ans, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(qtySkip, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(133, 133, 133))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qstText)
                    .addComponent(ans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton2))
                    .addComponent(qtySkip, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minigames/education_calculator_maths_math_icon_149699 (1).png"))); // NOI18N
        jLabel3.setText("Aritmatika");

        freeTest.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        freeTest.setText("Free Test");
        freeTest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                freeTestMouseClicked(evt);
            }
        });

        exit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        exit.setText("Exit");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });

        turnament.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        turnament.setText("Turnament");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel3)
                        .addGap(143, 143, 143)
                        .addComponent(freeTest)
                        .addGap(18, 18, 18)
                        .addComponent(turnament, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(freeTest, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(turnament, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(103, 103, 103)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(181, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(765, 562));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void run(){
                
        int rand1 = 0;
        int rand2 = 0;
        
        String ops = getRandomOperation();
        
        this.result = 0;
        switch (ops) {
            case "+":
                rand1 = getRandomNumber100();
                rand2 = getRandomNumber100();
                this.result = rand1 + rand2;
                break;
                
            case "-":
                rand1 = getRandomNumber100();
                rand2 = getRandomNumber100();
                this.result = rand1 - rand2;
                break;
                
            case "*":
                   
                rand1 = getRandomNumber10();
                rand2 = getRandomNumber100();
                
                this.result = rand1 * rand2;
                break;
                
            case "/":
                
                rand1 = getRandomNumber100();
                rand2 = getRandomNumber100();
                
                if(((rand1%rand2)!=0) || ((rand1/rand2)<1)){
                    do{
                        rand1 = getRandomNumber100();
                        rand2 = getRandomNumber100();
                    }while(((rand1%rand2)!=0) || ((rand1/rand2)<1));   
                }
                
                this.result = rand1 / rand2;
                
                break;
            default:
        }
        
        // set qst
        qst = Integer.toString(rand1)+" "+ops+" "+Integer.toString(rand2);
        qstText.setText(qst);
        
    }
    
    // random number 1 - 100 digits
    private int getRandomNumber100(){
        Random random = new Random();
        int randomNumber = random.nextInt(100) + 1;
        return randomNumber;
    }
    
    // random number 1 - 10 digits
    private int getRandomNumber10(){
        Random random = new Random();
        int randomNumber = random.nextInt(10) + 1;
        return randomNumber;
    }
    
    // random operation
    public static String getRandomOperation() {
        String[] operations = {"+", "-", "*", "/"};
        Random random = new Random();
        int index = random.nextInt(operations.length);
        return operations[index];
    }
    
    private void checkAns(){
        
        if(ans.getText().equals("")){
            JOptionPane.showMessageDialog(null, "MOHON ISI DAHULU!", "Alert", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        String anss = ans.getText();
        int answare = Integer.parseInt(ans.getText());        
        
        if(this.result == answare){
            JOptionPane.showMessageDialog(null, "BENAR!", "Alert", JOptionPane.INFORMATION_MESSAGE);     
            ans.setText("");
            HasilTest ht = new HasilTest(qst, anss, this.result, true);
            hasilTestList.add(ht);
            run();
        }else{
            ans.setText("");
            JOptionPane.showMessageDialog(null, "SALAH!", "Alert", JOptionPane.INFORMATION_MESSAGE);  
            HasilTest ht = new HasilTest(qst, anss, this.result, false);
            hasilTestList.add(ht);
            run();
        }
        this.qtySoal--;
        if(this.qtySoal<1){
            JOptionPane.showMessageDialog(null, "Soal Habis!", "Alert", JOptionPane.INFORMATION_MESSAGE);  
            Result result = new Result(hasilTestList);
            this.hide(); 
            result.setVisible(true);
        }
    }
    
    // regex just number
    class NumericDocumentFilter extends DocumentFilter {
        @Override
        public void insertString(FilterBypass fb, int offset, String string, AttributeSet attr) throws BadLocationException {
            if (isValidInteger(string, fb.getDocument().getText(0, fb.getDocument().getLength()), offset)) {
                super.insertString(fb, offset, string, attr);
            }
        }

        @Override
        public void replace(FilterBypass fb, int offset, int length, String text, AttributeSet attrs) throws BadLocationException {
            if (isValidInteger(text, fb.getDocument().getText(0, fb.getDocument().getLength()), offset)) {
                super.replace(fb, offset, length, text, attrs);
            }
        }

        @Override
        public void remove(FilterBypass fb, int offset, int length) throws BadLocationException {
            super.remove(fb, offset, length);
        }

        private boolean isValidInteger(String text, String currentText, int offset) {
            try {
                StringBuilder newText = new StringBuilder(currentText);
                newText.insert(offset, text);
                if (newText.toString().equals("-")) {
                    return true;
                }
                Integer.parseInt(newText.toString());
                return true;
            } catch (NumberFormatException e) {
                return false;
            }
        }
    }
    
    public class HasilTest{
        String qst;
        String ans;
        int result;
        boolean tf;
        
        public HasilTest(String qst, String ans, int result, boolean tf){
            this.qst = qst;
            this.ans = ans;
            this.result = result;
            this.tf = tf;
        }
        
        public void tampilkanData(){
//            JOptionPane.showMessageDialog(null, "Qst: " + this.qst + ", Ans: " + this.ans + ", Result: " + this.result,
//            "Info", JOptionPane.INFORMATION_MESSAGE);
            
            System.out.println("Qst: " + this.qst + ", Ans: " + this.ans + ", Result: " + this.result + ", true/false= " + this.tf);
        }
        
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(this.skip>0){
            run();
            this.skip--;
            qtySkip.setText("Kesempatan skip : "+Integer.toString(this.skip));
        }else{
            JOptionPane.showMessageDialog(null, "Kesempatan Skip Habis!", "Alert", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        checkAns();
    }//GEN-LAST:event_jButton2MouseClicked

    private void ansKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ansKeyReleased

    }//GEN-LAST:event_ansKeyReleased

    private void ansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ansActionPerformed
        checkAns();
    }//GEN-LAST:event_ansActionPerformed

    private void freeTestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_freeTestMouseClicked
        int dialogResult = JOptionPane.showConfirmDialog(null, "Keluar Turnamen?","Warning",JOptionPane.YES_NO_OPTION);
        System.out.println(dialogResult);
        if(dialogResult == JOptionPane.YES_OPTION){
            Aritmatika aritmatika = new Aritmatika();
            this.hide(); 
            aritmatika.setVisible(true);
        }
    }//GEN-LAST:event_freeTestMouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        int dialogResult = JOptionPane.showConfirmDialog(null, "Keluar app?","Warning",JOptionPane.YES_NO_OPTION);
        System.out.println(dialogResult);
        if(dialogResult == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_exitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Turnament.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Turnament.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Turnament.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Turnament.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Turnament().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ans;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel freeTest;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel qstText;
    private javax.swing.JLabel qtySkip;
    private javax.swing.JLabel turnament;
    // End of variables declaration//GEN-END:variables
}
